### ISSUE TITLE
SocketException: Write failed while doing pub get

### ISSUE THREAD

**Issue by tomaszkubacki** [dart-league/bootstrap_sass#1]
I've been following instructions from README 

and on pub get got:

Loading sass transformers... 
in ShutdownIsolate: Unhandled exception:
SocketException: Write failed, port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

^C
tomek@tora:~/projects/clay_tablet_connector_ui$ dart --version
**Dart VM version: 1.14.1 (Wed Feb  3 20:13:16 2016) on "linux_x64"**

**my pubspec:**
name: my_app
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.3
  browser: ^0.10.0
  bootstrap_sass: any
  sass: any
transformers:
- sass
- angular2:
  platform_directives:
  - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
  - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart

**Comment by tomaszkubacki** [comment]
Doesn't seem like a bootstrap_sass issue but sass itself - I think it can be closed

**Comment by tomaszkubacki** [comment]
it's just sass command not installed on my box. lame ;)  Worth metioning in README maybe

**Comment by luisvt** [comment]
Ok, I'll add it to Readme file
