### ISSUE TITLE
Use only grid and reset

### ISSUE THREAD

**Issue by advonesix** [dart-league/bootstrap_sass#10]
Hello,

I want to use only grid and reset. The rest of bootstrap will not be used in my project. Is there a way to configure it so that only those bootstrap modules are included? (similar to how pre-compiled bootstrap comes as three flavors - full, only grid, and only reset)

**Comment by luisvt** [comment]
yes, you need to follow the steps to create a custom theme with the difference that you only going to import `bootstrap_grid.scss` instead the full `bootstrap.scss` in your `them.scss` file:

```scss
import "package:bootstrap_sass/scss/bootstrap-reboot.scss";
import "package:bootstrap_sass/scss/bootstrap-grid.scss";

/* your styles here */
```
