### ISSUE TITLE
Upgrade to 4.0.0-beta2

### ISSUE THREAD

**Issue by BorisNaguet** [dart-league/bootstrap_sass#2]
Hello,
Bootstrap 4.0.0-beta2 has been out for a while with quite a lot of changes/corrections with beta-1.
It should be much closer to the final release, so it would be nice to upgrade this package.

Thanks

**Comment by luisvt** [comment]
fixed by https://github.com/dart-league/bootstrap_sass/commit/faa7b5fcf7d1419537a310e5da62dfa419e2f3ff
