### ISSUE TITLE
Importing bootstrap failed

### ISSUE THREAD

**Issue by fmatuszewski** [dart-league/bootstrap_sass#7]
This line of theme.scss failed for me
@import 'packages/bootstrap_sass/stylesheets/bootstrap';
with an error:
Error: Can't find stylesheet to import.
@import 'packages/bootstrap_sass/stylesheets/bootstrap';
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  - 2:9  root stylesheet

what is a correct path of bootstrap file:

theme.scss is
@import 'variables'; // variables should be before bootstrap to override variable values
@import 'packages/bootstrap_sass/stylesheets/bootstrap';
@import 'assets/styles/index';

pubspec.yaml is
name: shell
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.2
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  profile:
    path: ../profile
  communication:
    path: ../communication
  trip:
    path: ../trip
  places:
    path: ../places
  bezpieczenstwo:
    path: ../bezpieczenstwo
  rxdart: ^0.19.0
  bootstrap_sass: ^4.1.2 

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
  sass_builder: ^2.1.1

analyzer:
  errors:
    uri_has_not_been_generated: ignore

**Comment by luisvt** [comment]
sorry the correct import should be:

```scss
@import "package:bootstrap_sass/scss/bootstrap";
```

**Comment by fmatuszewski** [comment]
Now I get

**Comment by fmatuszewski** [comment]
`[SEVERE] sass_builder on web/theme.scss (cached):

Error: "package:" URLs aren't supported on this platform.
@import 'package:bootstrap_sass/scss/all';
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  - 2:9  root stylesheet
`

**Comment by fmatuszewski** [comment]
I use dart 2.0. May it be a problem?

**Comment by luisvt** [comment]
no, it shouldn't be a problem

**Comment by luisvt** [comment]
you can find a full example of `bootstrap_sass` used in a barebones app in next:

https://github.com/dart-league/bootstrap_sass/tree/master/example
