### ISSUE TITLE
Bootstrap 4.2 Spinners

### ISSUE THREAD

**Issue by pbarnum** [dart-league/bootstrap_sass#9]
Bootstrap 4.2 has new spinner classes ^_^
https://getbootstrap.com/docs/4.2/components/spinners/

**Comment by CedX** [comment]
Fixed by PR #8 : all we have to do is wait for a new package release.
In the meantime, you can still use this package: [bootstrap_bundle](https://pub.dartlang.org/packages/bootstrap_bundle)

**Comment by luisvt** [comment]
cool let me check

**Comment by luisvt** [comment]
I just released a new version, please check
